src/WhereMyMoney2/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;

namespace WhereMyMoney2.Controllers
{
    public class CategoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

src/WhereMyMoney2/Controllers/TraceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WhereMyMoney2.Models;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace WhereMyMoney2.Controllers
{
    public class TraceController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}   

src/WhereMyMoney2/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json;
@using WhereMyMoney.Models;

@if (Context.Session.Keys.Count() > 0)
{
    ViewBag.UserName = JsonConvert.DeserializeObject<SessionObject>(Context.Session.GetString("SessionObject")).UserName;
    ViewBag.IsAdmin = JsonConvert.DeserializeObject<SessionObject>(Context.Session.GetString("SessionObject")).IsAdmin;
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

    <title>Where Is My Money</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/wheremymoney2.css" />

    <script src="~/js/jquery.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script>

    <!-- 1. Load libraries -->
    <!-- IE required polyfills -->
    <script src="~/js/es6-shim.min.js"></script>
    <script src="~/js/system-polyfills.js"></script>

    <!-- Angular2 libraries -->
    <script src="~/js/angular2-polyfills.js"></script>
    <script src="~/js/system.src.js"></script>
    <script src="~/js/Rx.js"></script>
    <script src="~/js/angular2.js"></script>
    <script src="~/js/http.js"></script>
    <script src="~/js/router.js"></script>

    <!-- Bootstrap via SystemJS -->
    <script>
        System.config({
            packages: {
                "app": {
                    defaultExtension: 'js'
                }
            }
        });

        //Global variable
        var globalHost = '@(Context.Request.Scheme + "://" + Context.Request.Host)';
    </script>
    @RenderSection("angular_scripts", false)
</head>
<body>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <a asp-controller="Trace" asp-action="Index" class="navbar-brand"><span class="glyphicon glyphicon-user"></span> Wellcome @(ViewBag.UserName == null ? "to (Where Is My Money)" : ViewBag.UserName) !</a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-main">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse" id="navbar-main">
                <ul class="nav navbar-nav">
                    <li><a asp-controller="Trace" asp-action="Index">My Money</a></li>

                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Administration
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a asp-controller="User" asp-action="Index">User</a></li>
                            <li><a asp-controller="Currency" asp-action="Index">Currency</a></li>
                            <li><a asp-controller="Category" asp-action="Index">Category</a></li>
                        </ul>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a asp-controller="User" asp-action="ChangePassword"><span class="glyphicon glyphicon-barcode"></span> Change Password</a></li>
                    <li><a asp-controller="User" asp-action="LogOut"><span class="glyphicon glyphicon-off"></span> Sign Out</a></li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; Yumiki Studio 2016 - Where Is My Money v.2.0 - Theme by <a href="https://bootswatch.com/darkly/">Bootswatch Darkly</a></p>
        </footer>
    </div>
    @RenderSection("scripts", required: false)
</body>
</html>